theme: osuny-hugo-theme-aaa
params:
  logo:
    header: "/assets/images/logo-mmi.svg"
    footer: "/assets/images/logo-mmi.svg"
  seo:
    title:
      separator: "•"
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: true
  posts:
    index:
      layout: grid
  persons:
    single:
      backlinks: true
